# Generated by Django 2.2.4 on 2019-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_playing',
            field=models.IntegerField(default=False),
        ),
    ]
