# Generated by Django 2.2.4 on 2019-08-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190809_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='omok_main.Room'),
        ),
    ]
