# Generated by Django 2.2.4 on 2019-08-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190809_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_room',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
