# Generated by Django 2.2.4 on 2019-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255, null=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_waiting', models.BooleanField(default=False)),
                ('omok_board', models.TextField(default='', null=True)),
            ],
        ),
    ]
