# Generated by Django 2.2.4 on 2019-08-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('player1', models.CharField(default=None, max_length=255)),
                ('player2', models.CharField(default=None, max_length=255)),
                ('winner', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
