# Generated by Django 2.2.4 on 2019-08-09 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('player1', models.CharField(max_length=255, null=True)),
                ('player2', models.CharField(max_length=255, null=True)),
                ('winner', models.CharField(max_length=255, null=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('omok_board', models.TextField(default='', null=True)),
                ('player1_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
