# Generated by Django 2.2.4 on 2019-08-09 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omok_main', '0002_auto_20190809_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1_test',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2_test',
        ),
        migrations.AlterField(
            model_name='room',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_test', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_test', to=settings.AUTH_USER_MODEL),
        ),
    ]
