# Generated by Django 2.2.4 on 2019-08-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok_main', '0002_auto_20190807_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
