# Generated by Django 2.2.4 on 2019-08-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok_main', '0003_room_is_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='omok_board',
            field=models.TextField(default='', null=True),
        ),
    ]
